apiVersion: 1

datasources:
  - name: InfluxDB-k6
    uid: influxdb-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true

    jsonData:
      version: Flux
      organization: stress-platform
      defaultBucket: k6
      tlsSkipVerify: true

    secureJsonData:
      token: ${INFLUXDB_TOKEN}