{
 "title": "Dashboard ST POC",
 "time": { "from": "2026-08-31T23:46:10.308Z", "to": "2026-08-31T23:48:19.292Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "execution_id",
    "query": {
     "query": "from(bucket: \"k6-stress-tests\")   \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)   \r\n  |> filter(fn: (r) => exists r.execution_id)   \r\n  |> keep(columns: [\"execution_id\"])   \r\n  |> rename(columns: {execution_id: \"_value\"})   \r\n  |> group()   \r\n  |> unique(column: \"_value\")   \r\n  |> sort(columns: [\"_value\"], desc: true)"
    }
   },
   { "name": "bucket", "query": "k6-stress-tests" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> keep(columns: [\"_time\", \"test_name\"])\r\n  |> rename(columns: {test_name: \"_value\"})\r\n  |> group()\r\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> keep(columns: [\"_time\", \"application\"])\r\n  |> rename(columns: {application: \"_value\"})\r\n  |> group()\r\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> keep(columns: [\"_time\", \"environment\"])\r\n  |> rename(columns: {environment: \"_value\"})\r\n  |> group()\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Active Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vus\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> set(key: \"_field\", value: \"Active VUs\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  // Junta todas as séries (status, url, método, etc.)\r\n  |> group(columns: [\"execution_id\"])\r\n  // Soma as requisições por segundo\r\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> set(key: \"_field\", value: \"Throughput\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> set(key: \"_field\", value: \"Response Time\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> filter(fn: (r) => int(v: r.status) >= 400)\r\n\r\n  |> group(columns: [\"execution_id\"])\r\n\r\n  // Conta erros por segundo\r\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: true)\r\n\r\n  // Segundos sem erro = 0\r\n  |> fill(column: \"_value\", value: 0)\r\n\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> set(key: \"_field\", value: \"Failed Requests/sec\")"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n\r\n  // Junta todas as séries da execução\r\n  |> group(columns: [\"execution_id\"])\r\n\r\n  // Média única\r\n  |> mean()\r\n\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> group()\r\n  |> quantile(q: 0.90, method: \"estimate_tdigest\")"
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> group()\r\n  |> quantile(q: 0.95, method: \"estimate_tdigest\")"
    }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> group()\r\n  |> quantile(q: 0.99, method: \"estimate_tdigest\")"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n\r\n  // Junta todas as séries (status, url, método...)\r\n  |> group(columns: [\"execution_id\"])\r\n\r\n  // Soma todas as requisições do período\r\n  |> sum(column: \"_value\")\r\n\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n\r\n  |> group(columns: [\"execution_id\"])\r\n\r\n  // Requisições por segundo\r\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: false)\r\n\r\n  // Média do throughput ao longo do teste\r\n  |> mean()\r\n\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_failed\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> group(columns: [\"execution_id\"])\r\n  |> mean()\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Requests x Status x Total Req x Avg/Max RT",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n\r\n  |> group(columns: [\"name\", \"status\"])\r\n\r\n  |> reduce(\r\n    identity: {\r\n      Requests: 0,\r\n      Total: 0.0,\r\n      Max: 0.0,\r\n      Name: \"\",\r\n      Status: \"\"\r\n    },\r\n    fn: (r, accumulator) => ({\r\n      Requests: accumulator.Requests + 1,\r\n      Total: accumulator.Total + r._value,\r\n      Max: if r._value > accumulator.Max then r._value else accumulator.Max,\r\n      Name: r.name,\r\n      Status: string(v: r.status)\r\n    })\r\n  )\r\n\r\n  |> map(fn: (r) => ({\r\n      Request: r.Name,\r\n      Status: r.Status,\r\n      \"Total Requests\": r.Requests,\r\n      Avg_rt: r.Total / float(v: r.Requests),\r\n      Max_rt: r.Max\r\n  }))\r\n\r\n  |> keep(columns: [\"Request\", \"Status\", \"Total Requests\", \"Avg_rt\", \"Max_rt\"])\r\n  |> sort(columns: [\"Request\", \"Status\"])"
    }
   ]
  }
 ]
}