{
 "title": "Dashboard ST POC",
 "time": { "from": "2026-08-29T01:23:40.916Z", "to": "2026-08-29T01:29:28.244Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "execution_id",
    "query": {
     "query": "from(bucket: \"k6-stress-tests\")   \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)   \r\n  |> filter(fn: (r) => exists r.execution_id)   \r\n  |> keep(columns: [\"execution_id\"])   \r\n  |> rename(columns: {execution_id: \"_value\"})   \r\n  |> group()   \r\n  |> unique(column: \"_value\")   \r\n  |> sort(columns: [\"_value\"], desc: true)"
    }
   },
   { "name": "bucket", "query": "k6-stress-tests" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> keep(columns: [\"_time\", \"test_name\"])\r\n  |> rename(columns: {test_name: \"_value\"})\r\n  |> group()\r\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> keep(columns: [\"_time\", \"application\"])\r\n  |> rename(columns: {application: \"_value\"})\r\n  |> group()\r\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> keep(columns: [\"_time\", \"environment\"])\r\n  |> rename(columns: {environment: \"_value\"})\r\n  |> group()\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Active Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vus\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> set(key: \"_field\", value: \"Active VUs\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: true)\r\n  |> fill(column: \"_value\", value: 0.0)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> set(key: \"_field\", value: \"Throughput\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> set(key: \"_field\", value: \"Response Time\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n\r\n  // Mantém qualquer erro HTTP (4xx e 5xx)\r\n  |> filter(fn: (r) => int(v: r.status) >= 400)\r\n\r\n  // Conta quantas ocorreram em cada janela\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: true)\r\n\r\n  // Preenche janelas sem erro com zero\r\n  |> fill(column: \"_value\", value: 0)\r\n\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> set(key: \"_field\", value: \"Failed Requests/sec\")"
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> group()\r\n  |> quantile(q: 0.99, method: \"estimate_tdigest\")"
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> group()\r\n  |> quantile(q: 0.95, method: \"estimate_tdigest\")"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.execution_id == \"${execution_id}\")\r\n  |> group()\r\n  |> quantile(q: 0.90, method: \"estimate_tdigest\")"
    }
   ]
  }
 ]
}